# sources:
# - https://github.com/docker/build-push-action/blob/master/docs/advanced/push-multi-registries.md
# - https://github.community/t/how-to-get-just-the-tag-name/16241/6

name: ci

on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Extract tag
        id: extract_tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            raphaeljoie/python-lambda-builder:latest
            raphaeljoie/python-lambda-builder:${{ steps.extract_tag.outputs.TAG }}
            ghcr.io/raphaeljoie/python-lambda-builder:latest
            ghcr.io/raphaeljoie/python-lambda-builder:${{ steps.extract_tag.outputs.TAG }}
